name: Destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Switch to terraform folder
        run: |
          cd terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Set AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
        run: |
          export AWS_REGION
      - name: Format Terraform code
        run: terraform fmt
      - name: Validate Terraform code
        run: terraform validate
      - name: Initialize Terraform
        run: terraform init
      - name: Destroy Terraform
        run: terraform destroy -var-file dev.tfvars