name: destroy
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  destroy:
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install terraform
        run: sudo snap install terraform --classic
      - name: Enable aws credentials from secrets to environment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
        run: |
          export AWS_ACCESS_KEY_ID
          export AWS_SECRET_ACCESS_KEY
          export AWS_REGION
      - name: Terraform fmt
        run: terraform fmt
      - name: Terraform validate
        run: terraform validate
      - name: Terraform init
        run: terraform init
      - name: Terraform destroy
        run: terraform destroy