name: Destroy
on:
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Terraform workspace (e.g. dev, prod)'
        required: true
        default: 'dev'
defaults:
  run:
    working-directory: terraform
jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-west-2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform fmt
        run: terraform fmt
      - name: Terraform init
        run: terraform init
      - name: Select or create workspace
        run: |
          terraform workspace select ${{ github.event.inputs.workspace }} || terraform workspace new ${{ github.event.inputs.workspace }}
      - name: Terraform validate
        run: terraform validate
      - name: Terraform destroy
        run: terraform destroy -var-file=${{ github.event.inputs.workspace }}.tfvars -auto-approve