name: Destroy

on:
  workflow_dispatch:
defaults:
  run:
    working-directory: terraform
jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Enable AWS credentials
        env:
          AWS_REGION: us-west-2
        run: |
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - name: Terraform fmt
        run: terraform fmt
      - name: Terraform validate
        run: terraform validate
      - name: Terraform init
        run: terraform init
      - name: Terraform destroy
        run: terraform destroy