name: Plan and Apply

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  plan_and_apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Switch to terraform folder
        run: |
          cd terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Set AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
        run: |
          export AWS_REGION
          export AWS_ACCESS_KEY_ID
          export AWS_SECRET_ACCESS_KEY
      - name: Format Terraform code
        run: terraform fmt
      - name: Validate Terraform code
        run: terraform validate
      - name: Initialize Terraform
        run: terraform init
      - name: Plan Terraform
        run: terraform plan -var-file dev.tfvars
      - name: Apply Terraform
        run: terraform apply -var-file dev.tfvars