name: Plan and Apply

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

defaults:
  run:
    working-directory: terraform

jobs:
  plan_and_apply:
    runs-on: ubuntu-latest
    env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform fmt
        run: terraform fmt
      - name: Terraform init
        run: terraform init
      - name: Terraform validate
        run: terraform validate
      - name: Terraform plan
        run: terraform plan -var-file=dev.tfvars
      - name: Terraform apply on merge
        if: github.event.pull_request.merged
        run: terraform apply