name: plan-apply

on:
  pull_request:
    branches:
      - master

jobs:
  plan-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Switch to terraform folder
        run: cd terraform

      - name: Install terraform
        run: curl -s https://apt.puppetlabs.com/apt-puppetlabs-stretch.sh | sh | terraform

      - name: Set AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
        run: |
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          export AWS_REGION=$AWS_REGION

      - name: Terraform fmt
        run: terraform fmt

      - name: Terraform validate
        run: terraform validate

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -var-file=dev.tfvars

      - name: Wait for PR review
        if: github.event.pull_request.review_status == 'APPROVED'
        run: terraform apply -var-file=dev.tfvars